<?php
return [
    [
        'name'=>'域名管理',
        'url'=>'',
        'icon'=>'Hui-iconfont-hetong',
        'children'=>[
            [
                'name'=>'域名列表',
                'url'=>'/admin/domain/index',
                'icon'=>'',
            ],
        ]
    ],
    [
        'name'=>'日志管理',
        'url'=>'',
        'icon'=>'Hui-iconfont-quanbudingdan',
        'children'=>[
            [
                'name'=>'邮件记录',
                'url'=>'/admin/log/email',
                'icon'=>'',
            ],
        ]
    ],
    [
        'name'=>'系统管理',
        'url'=>'',
        'icon'=>'Hui-iconfont-system',
        'children'=>[
            [
                'name'=>'通知账号管理',
                'url'=>'/admin/sys/user',
                'icon'=>'',
            ],
            [
                'name'=>'邮箱配置',
                'url'=>'/admin/sys/email',
                'icon'=>'',
            ],
        ]
    ],
];